kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-1
  labels:
    type: local
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/hd1/wordpress
    server: 172.16.64.238
  persistentVolumeReclaimPolicy: Retain
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-2
  labels:
    type: local
spec:
  capacity:
    storage: 500Mi 
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/hd1/wordpress
    server: 172.16.64.238
  persistentVolumeReclaimPolicy: Retain
